name: CI/CD Pipeline
on: 
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
jobs:
    format-lint:
        name: Format and lint errors
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: ['21.x']
        steps:
        - uses: actions/checkout@v4
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v4
          with:
            node-version: ${{ matrix.node-version }}
        - name: Install pnpm
          uses: pnpm/action-setup@v3
          with:
            version: 8.15.1
            run_install: true
        - name: pnpm format
          run: pnpm run format && pnpm run lint
    unit-tests:
        name: Unit Tests
        needs: format-lint
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: ['21.x']
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.node-version }}
            - name: Install pnpm
              uses: pnpm/action-setup@v3
              with:
                version: 8.15.1
                run_install: true
            - name: pnpm test
              run: pnpm test
    e2e-tests:
        name: Integration tests
        needs: unit-tests
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: ['21.x']
        env:
          APP_ENV: "test"
          DATABASE_URI: ${{ secrets.DATABASE_URI }}
          CONTENTFUL_API_ACCESSTOKEN: ${{ secrets.CONTENTFUL_API_ACCESSTOKEN }}
          CONTENTFUL_API_CONTENTTYPE: ${{ secrets.CONTENTFUL_API_CONTENTTYPE }}
          CONTENTFUL_API_ENVIRONMENT: ${{ secrets.CONTENTFUL_API_ENVIRONMENT }}
          CONTENTFUL_API_SPACEID: ${{ secrets.CONTENTFUL_API_SPACEID }}
          CONTENTFUL_API_URL: ${{ secrets.CONTENTFUL_API_URL }}
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.node-version }}
            - name: Install pnpm
              uses: pnpm/action-setup@v3
              with:
                version: 8.15.1
                run_install: true
            - name: pnpm test integration
              run: pnpm run test:e2e